# Configure preferences
# 配置偏好设置
preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

# Configure repositories used by dependencies
# 配置依赖使用的存储库
repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  google:
  maven-central:
  # 作为 Xposed 模块使用务必添加，其它情况可选
  rovo89-xposed-api:
    url: https://api.xposed.info/
  jitpack:
    url: https://jitpack.io/

plugins:
  # 作为 Xposed 模块使用务必添加，其它情况可选
  com.google.devtools.ksp:
    version: 2.0.20-1.0.25
  org.jetbrains.kotlin.android:
    version: 2.0.20
  org.jetbrains.kotlin.plugin.serialization:
    version: 2.0.20

libraries:
  # 作为 Xposed 模块使用务必添加，其它情况可选
  de.robv.android.xposed:
    api:
      version: 82
      repositories:
        rovo89-xposed-api
  com.highcapable.yukihookapi:
    api:
      version: 1.2.1
    # 作为 Xposed 模块使用务必添加，其它情况可选
    ksp-xposed:
      version-ref: <this>::api
  org.jetbrains.kotlinx:
    kotlinx-serialization-json:
      version: 1.7.3