# SweetDependency project configuration file
# You can adjust your custom configuration to your liking here
# You can visit https://github.com/HighCapable/SweetDependency for more help
#
# SweetDependency 项目配置文件
# 你可以在这里调整你喜欢的自定义配置
# 你可以前往 https://github.com/HighCapable/SweetDependency 以获得更多帮助

# Configure preferences
# 配置偏好设置
preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

# Configure repositories used by dependencies
# 配置依赖使用的存储库
repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  google:
  maven-central:
  # 作为 Xposed 模块使用务必添加，其它情况可选
  rovo89-xposed-api:
    url: https://api.xposed.info/
  jitpack:
    url: https://jitpack.io/

# Configure plugins that need to be used
# For example:
# plugins:
#   org.jetbrains.kotlin.jvm:
#     version: +
#
# 配置需要使用的插件依赖
# 例如:
# plugins:
#   org.jetbrains.kotlin.jvm:
#     version: +
plugins:
  # 作为 Xposed 模块使用务必添加，其它情况可选
  com.google.devtools.ksp:
    version: 2.0.20-1.0.25
  org.jetbrains.kotlin.android:
    version: 2.0.20

# Configure libraries that need to be used
# For example:
# libraries:
#   com.google.code.gson:
#     gson:
#       version: +
#
# 配置需要使用的库依赖
# 例如:
# libraries:
#   com.google.code.gson:
#     gson:
#       version: +
libraries:
  # 作为 Xposed 模块使用务必添加，其它情况可选
  de.robv.android.xposed:
    api:
      version: 82
      repositories:
        rovo89-xposed-api
  com.highcapable.yukihookapi:
    api:
      version: 1.2.1
    # 作为 Xposed 模块使用务必添加，其它情况可选
    ksp-xposed:
      version-ref: <this>::api